name: mil100fe-ml-ga
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - xgboost
  - openpyxl
  - scipy
  - plotly
  - shap
  - pip
  - pip:
      - deap
      - pyswarm
      - scikit-opt
